# Generated by Django 6.0.7 on 2026-07-07 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id_siebel', models.CharField(db_index=True, max_length=32)),
                ('product_name', models.CharField(max_length=200)),
                ('family', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.CharField(blank=True, default='', max_length=100)),
                ('price_emission', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_emission_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_gross_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_net_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('currency_local', models.CharField(blank=True, default='', max_length=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('geographic_scope', models.CharField(blank=True, default='', max_length=100)),
                ('age_limit_lower', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_limit_upper', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto cotizado',
                'verbose_name_plural': 'Productos cotizados',
                'ordering': ['price_emission_local', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('visible_name', models.CharField(blank=True, default='', max_length=300)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='quotes.quoteproduct')),
            ],
            options={
                'verbose_name': 'Atributo de cobertura',
                'verbose_name_plural': 'Atributos de cobertura',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TravelQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_id_siebel', models.CharField(blank=True, default='', max_length=32)),
                ('quote_count', models.PositiveSmallIntegerField(default=0)),
                ('affiliate_type', models.CharField(choices=[('INDIVIDUAL', 'No asociado'), ('CAVIPETROL', 'Asociado Cavipetrol')], default='INDIVIDUAL', max_length=16)),
                ('origin_country', models.CharField(default='COLOMBIA', max_length=50)),
                ('destination_ui_code', models.CharField(blank=True, default='', max_length=50)),
                ('destination_siebel', models.CharField(max_length=100)),
                ('trip_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('passenger_count', models.PositiveSmallIntegerField()),
                ('passenger_ages', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('contact_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('QUOTED', 'Cotizada'), ('EXPIRED', 'Expirada'), ('SELECTED', 'Plan seleccionado'), ('CONVERTED', 'Convertida')], db_index=True, default='DRAFT', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_quotes', to='quotes.quoteproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización de viaje',
                'verbose_name_plural': 'Cotizaciones de viaje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quoteproduct',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quotes.travelquote'),
        ),
        migrations.AddIndex(
            model_name='travelquote',
            index=models.Index(fields=['user', 'status'], name='quotes_trav_user_id_9f4e87_idx'),
        ),
        migrations.AddIndex(
            model_name='travelquote',
            index=models.Index(fields=['user', 'expires_at'], name='quotes_trav_user_id_554cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteproduct',
            index=models.Index(fields=['quote', 'product_id_siebel'], name='quotes_quot_quote_i_3c0b8c_idx'),
        ),
    ]
