# Generated by Django 6.0.7 on 2026-07-07 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=30)),
                ('document_number', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('residence_country', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='quotes.travelquote')),
            ],
            options={
                'verbose_name': 'Pasajero de cotización',
                'verbose_name_plural': 'Pasajeros de cotización',
                'ordering': ['sort_order', 'last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('quote', 'sort_order'), name='quotes_passenger_unique_sort_order')],
            },
        ),
    ]
