# Generated by Django 6.0.7 on 2026-07-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_autoquote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autoquote',
            new_name='quotes_auto_user_id_0d06b8_idx',
            old_name='quotes_auto_user_id_0f2c0a_idx',
        ),
        migrations.RenameIndex(
            model_name='autoquote',
            new_name='quotes_auto_user_id_9c5dfb_idx',
            old_name='quotes_auto_user_id_7c1e2b_idx',
        ),
        migrations.RenameIndex(
            model_name='autoquote',
            new_name='quotes_auto_vehicle_19b265_idx',
            old_name='quotes_auto_vehicle_9d4a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='autoquotepackage',
            new_name='quotes_auto_quote_i_992bb8_idx',
            old_name='quotes_auto_quote_i_3b8f2d_idx',
        ),
    ]
