from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0006_cavipetrol_affiliation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affiliate_type', models.CharField(choices=[('INDIVIDUAL', 'No asociado'), ('CAVIPETROL', 'Asociado Cavipetrol')], default='INDIVIDUAL', max_length=16)),
                ('affiliation_number', models.CharField(blank=True, default='', max_length=40)),
                ('payment_form', models.CharField(blank=True, default='', max_length=40)),
                ('paying_company', models.CharField(blank=True, default='', max_length=120)),
                ('product_code', models.CharField(default='2013', max_length=8)),
                ('risk_category', models.CharField(default='3', max_length=1)),
                ('locality_dane_code', models.CharField(default='11001', max_length=10)),
                ('city_name', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('address_extra', models.CharField(blank=True, default='', max_length=120)),
                ('building_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contents_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('theft_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('all_risk_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pet_coverage', models.CharField(default='NO', max_length=4)),
                ('construction_year', models.PositiveSmallIntegerField()),
                ('total_floors', models.PositiveSmallIntegerField(default=1)),
                ('apartment_floor', models.PositiveSmallIntegerField(default=1)),
                ('basements', models.PositiveSmallIntegerField(default=0)),
                ('area_sqm', models.PositiveIntegerField(default=50)),
                ('construction_type', models.CharField(default='3', max_length=4)),
                ('housing_type', models.CharField(default='2', max_length=4)),
                ('payment_frequency', models.CharField(default='A', max_length=1)),
                ('holder_doc_type', models.CharField(default='C', max_length=4)),
                ('holder_doc_number', models.CharField(max_length=32)),
                ('is_holder_owner', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('term_date', models.DateField()),
                ('allianz_quotation_number', models.CharField(blank=True, default='', max_length=64)),
                ('risk_type_desc', models.CharField(blank=True, default='', max_length=120)),
                ('contact_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('QUOTED', 'Cotizada'), ('EXPIRED', 'Expirada'), ('SELECTED', 'Plan seleccionado'), ('ASSIGNED', 'Asignada a comercial'), ('CONVERTED', 'Convertida')], db_index=True, default='DRAFT', max_length=16)),
                ('app_reference', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('insurer_reference', models.CharField(blank=True, default='', max_length=64)),
                ('insurer_name', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_commercial_name', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_commercial_email', models.EmailField(blank=True, default='', max_length=254)),
                ('assigned_commercial_title', models.CharField(blank=True, default='', max_length=120)),
                ('client_notified_at', models.DateTimeField(blank=True, null=True)),
                ('commercial_notified_at', models.DateTimeField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización de hogar',
                'verbose_name_plural': 'Cotizaciones de hogar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeQuotePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_id', models.CharField(db_index=True, max_length=32)),
                ('product_id_siebel', models.CharField(db_index=True, max_length=32)),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, default='Allianz', max_length=100)),
                ('logo', models.CharField(blank=True, default='allianz', max_length=100)),
                ('price_emission', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_emission_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_gross_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_net_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium_semestral', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium_trimestral', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='COP', max_length=10)),
                ('currency_local', models.CharField(blank=True, default='COP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='quotes.homequote')),
            ],
            options={
                'verbose_name': 'Paquete hogar cotizado',
                'verbose_name_plural': 'Paquetes hogar cotizados',
                'ordering': ['price_emission_local', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='HomeQuoteCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_id', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(max_length=300)),
                ('visible_name', models.CharField(blank=True, default='', max_length=300)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('deductible', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='quotes.homequotepackage')),
            ],
            options={
                'verbose_name': 'Cobertura hogar',
                'verbose_name_plural': 'Coberturas hogar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='homequote',
            name='selected_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_quotes', to='quotes.homequotepackage'),
        ),
        migrations.AddIndex(
            model_name='homequote',
            index=models.Index(fields=['user', 'status'], name='quotes_home_user_id_status_idx'),
        ),
        migrations.AddIndex(
            model_name='homequote',
            index=models.Index(fields=['user', 'expires_at'], name='quotes_home_user_id_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='homequotepackage',
            index=models.Index(fields=['quote', 'package_id'], name='quotes_home_quote_pkg_idx'),
        ),
    ]
