services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/insurance_db
      - REDIS_URL=redis://redis:6379/0
      - EMAIL_USE_SMTP=${EMAIL_USE_SMTP:-true}
      - EMAIL_HOST=${EMAIL_HOST:-mail.sensedigital.com.co}
      - EMAIL_PORT=${EMAIL_PORT:-465}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL:-true}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-false}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-casse@sensedigital.com.co}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-@SenseCamilo2025}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-casse@sensedigital.com.co}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:

