# Generated by Django 6.0.1 on 2026-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('DELETED', 'Eliminado')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
    ]
