# Generated by Django 6.0.3 on 2026-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_deleted_at_alter_user_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_primary',
            field=models.EmailField(max_length=254, verbose_name='Email Principal'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DELETED'), _negated=True), fields=('id_type', 'id_number'), name='unique_id_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DELETED'), _negated=True), fields=('email_primary',), name='unique_email_not_deleted'),
        ),
    ]
