# Generated by Django 6.0.3 on 2026-03-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_unique_together_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('DELETED', 'Eliminado'), ('PENDING_VERIFICATION', 'Pendiente verificación')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
    ]
