# Generated by Django 6.0.3 on 2026-03-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('DELETED', 'Eliminado')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
    ]
