"""
Constants for audit log actions.
"""
# Authentication actions
LOGIN_SUCCESS = 'LOGIN_SUCCESS'
LOGIN_FAILED = 'LOGIN_FAILED'
LOGOUT = 'LOGOUT'
OTP_SENT = 'OTP_SENT'
OTP_VERIFIED = 'OTP_VERIFIED'
OTP_FAILED = 'OTP_FAILED'
OTP_EXPIRED = 'OTP_EXPIRED'
OTP_RESENT = 'OTP_RESENT'
PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED'
PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED'
PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED'
PASSWORD_CHANGED = 'PASSWORD_CHANGED'

# User management actions
USER_REGISTERED = 'USER_REGISTERED'
USER_CREATED_BY_ADMIN = 'USER_CREATED_BY_ADMIN'
USER_UPDATED_BY_ADMIN = 'USER_UPDATED_BY_ADMIN'
USER_UPDATED_SELF = 'USER_UPDATED_SELF'
USER_SUSPENDED = 'USER_SUSPENDED'
USER_ACTIVATED = 'USER_ACTIVATED'
USER_DELETED = 'USER_DELETED'
USER_DELETED_SELF = 'USER_DELETED_SELF'
USER_REACTIVATED = 'USER_REACTIVATED'

# Policy actions (for future use)
POLICY_CREATED = 'POLICY_CREATED'
POLICY_UPDATED = 'POLICY_UPDATED'
POLICY_DELETED = 'POLICY_DELETED'

# Payment actions (for future use)
PAYMENT_CREATED = 'PAYMENT_CREATED'
PAYMENT_COMPLETED = 'PAYMENT_COMPLETED'
PAYMENT_FAILED = 'PAYMENT_FAILED'

