# Generated by Django 6.0.7 on 2026-07-07 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('quotes', '0002_quotepassenger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_number_siebel', models.CharField(blank=True, default='', max_length=32)),
                ('control_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ISSUING', 'Emitiendo'), ('ISSUED', 'Emitido'), ('ERROR', 'Error'), ('CANCELLED', 'Anulado')], db_index=True, default='PENDING', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('pdf_path', models.CharField(blank=True, default='', max_length=500)),
                ('raw_alta_response', models.JSONField(blank=True, default=dict)),
                ('raw_portal_response', models.JSONField(blank=True, default=dict)),
                ('raw_report_response', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='payments.payment')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='quotes.travelquote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher de viaje',
                'verbose_name_plural': 'Vouchers de viaje',
                'ordering': ['-created_at'],
            },
        ),
    ]
