# Generated by Django 5.2.6 on 2026-07-07 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationCallLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_name", models.CharField(db_index=True, max_length=64)),
                ("operation", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Éxito"),
                            ("ERROR", "Error"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de integración",
                "verbose_name_plural": "Logs de integración",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service_name", "operation"],
                        name="integration_service_945588_idx",
                    ),
                    models.Index(
                        fields=["created_at", "status"],
                        name="integration_created_001ae6_idx",
                    ),
                ],
            },
        ),
    ]
