# Generated by Django 5.2.6 on 2026-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DestinationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ui_code", models.CharField(max_length=50, unique=True)),
                ("ui_label", models.CharField(max_length=100)),
                ("siebel_value", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Mapeo de destino",
                "verbose_name_plural": "Mapeos de destino",
                "ordering": ["sort_order", "ui_label"],
            },
        ),
        migrations.CreateModel(
            name="CatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalog_type",
                    models.CharField(
                        choices=[
                            ("DESTINATION", "Destino"),
                            ("TRIP_TYPE", "Tipo de viaje"),
                            ("COUNTRY", "País"),
                            ("DOCUMENT_TYPE", "Tipo de documento"),
                            ("CHANNEL", "Canal"),
                            ("SALE_TYPE", "Tipo de venta"),
                            ("GENDER", "Sexo"),
                            ("VOUCHER_STATUS", "Estado voucher"),
                            ("PAYMENT_METHOD", "Medio de pago"),
                            ("COURTESY_TITLE", "Título cortesía"),
                            ("REASON_CODE", "Código de razón"),
                            ("BILLING", "Facturación"),
                            ("LINE", "Línea"),
                            ("VOUCHER_REASON", "Motivo voucher"),
                            ("ISSUER", "Emisor"),
                            ("CURRENCY", "Moneda"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Entrada de catálogo",
                "verbose_name_plural": "Entradas de catálogo",
                "ordering": ["catalog_type", "sort_order", "label"],
                "indexes": [
                    models.Index(
                        fields=["catalog_type", "is_active"],
                        name="catalogs_ca_catalog_506cbb_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog_type", "code"), name="uniq_catalog_type_code"
                    )
                ],
            },
        ),
    ]
